/*
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated at 01/07/2021 13:20:52.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Matroska.Models2
{
    public sealed class AttachedFile
    {
        }

    public sealed class Attachments
    {
        }

    public sealed class Audio
    {
        }

    public sealed class BlockAdditionMapping
    {
        }

    public sealed class BlockAdditions
    {
        }

    public sealed class BlockGroup
    {
        }

    public sealed class BlockMore
    {
        }

    public sealed class ChapProcess
    {
        }

    public sealed class ChapProcessCommand
    {
        }

    public sealed class ChapterAtom
    {
        }

    public sealed class ChapterDisplay
    {
        }

    public sealed class Chapters
    {
        }

    public sealed class ChapterTrack
    {
        }

    public sealed class ChapterTranslate
    {
        }

    public sealed class Cluster
    {
        }

    public sealed class Colour
    {
        }

    public sealed class ContentCompression
    {
        }

    public sealed class ContentEncAESSettings
    {
        }

    public sealed class ContentEncoding
    {
        }

    public sealed class ContentEncodings
    {
        }

    public sealed class ContentEncryption
    {
        }

    public sealed class CuePoint
    {
        }

    public sealed class CueReference
    {
        }

    public sealed class Cues
    {
        }

    public sealed class CueTrackPositions
    {
        }

    public sealed class EditionEntry
    {
        }

    public sealed class Info
    {
        }

    public sealed class MasteringMetadata
    {
        }

    public sealed class Projection
    {
        }

    public sealed class ReferenceFrame
    {
        }

    public sealed class Seek
    {
        }

    public sealed class SeekHead
    {
        }

    public sealed class Segment
    {
        }

    public sealed class SilentTracks
    {
        }

    public sealed class SimpleTag
    {
        }

    public sealed class Slices
    {
        }

    public sealed class Tag
    {
        }

    public sealed class Tags
    {
        }

    public sealed class Targets
    {
        }

    public sealed class TimeSlice
    {
        }

    public sealed class TrackCombinePlanes
    {
        }

    public sealed class TrackEntry
    {
        }

    public sealed class TrackJoinBlocks
    {
        }

    public sealed class TrackOperation
    {
        }

    public sealed class TrackPlane
    {
        }

    public sealed class Tracks
    {
        }

    public sealed class TrackTranslate
    {
        }

    public sealed class Video
    {
        }

}
*/