/*
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated at 01/07/2021 13:08:58.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Matroska.Models2
{
    public sealed class AttachedFile
    {
            public byte[]? FileData { get; set; }
        public string? FileDescription { get; set; }
        public string FileMimeType { get; set; }
        public string FileName { get; set; }
        public byte[]? FileReferral { get; set; }
        public ulong FileUID { get; set; }
        public ulong? FileUsedEndTime { get; set; }
        public ulong? FileUsedStartTime { get; set; }
    }

    public sealed class Attachments
    {
            public byte[]? FileData { get; set; }
        public string? FileDescription { get; set; }
        public string FileMimeType { get; set; }
        public string FileName { get; set; }
        public byte[]? FileReferral { get; set; }
        public ulong FileUID { get; set; }
        public ulong? FileUsedEndTime { get; set; }
        public ulong? FileUsedStartTime { get; set; }
    }

    public sealed class Audio
    {
            public ulong? BitDepth { get; set; }
        public byte[]? ChannelPositions { get; set; }
        public ulong Channels { get; set; }
        public float? OutputSamplingFrequency { get; set; }
        public float SamplingFrequency { get; set; }
    }

    public sealed class BlockAdditionMapping
    {
            public byte[]? BlockAddIDExtraData { get; set; }
        public string? BlockAddIDName { get; set; }
        public ulong BlockAddIDType { get; set; }
        public ulong? BlockAddIDValue { get; set; }
    }

    public sealed class BlockAdditions
    {
            public ulong BlockAddID { get; set; }
        public byte[]? BlockAdditional { get; set; }
    }

    public sealed class BlockGroup
    {
            public ulong BlockAddID { get; set; }
        public byte[]? BlockAdditional { get; set; }
        public ulong? BlockAdditionID { get; set; }
        public ulong? BlockDuration { get; set; }
        public byte[]? BlockVirtual { get; set; }
        public byte[]? CodecState { get; set; }
        public ulong? Delay { get; set; }
        public long? DiscardPadding { get; set; }
        public ulong? FrameNumber { get; set; }
        public ulong? LaceNumber { get; set; }
        public long? ReferenceBlock { get; set; }
        public ulong ReferenceOffset { get; set; }
        public ulong ReferencePriority { get; set; }
        public ulong ReferenceTimestamp { get; set; }
        public long? ReferenceVirtual { get; set; }
        public ulong? SliceDuration { get; set; }
    }

    public sealed class BlockMore
    {
            public ulong BlockAddID { get; set; }
        public byte[]? BlockAdditional { get; set; }
    }

    public sealed class ChapProcess
    {
            public ulong ChapProcessCodecID { get; set; }
        public byte[]? ChapProcessData { get; set; }
        public byte[]? ChapProcessPrivate { get; set; }
        public ulong ChapProcessTime { get; set; }
    }

    public sealed class ChapProcessCommand
    {
            public byte[]? ChapProcessData { get; set; }
        public ulong ChapProcessTime { get; set; }
    }

    public sealed class ChapterAtom
    {
        }

    public sealed class ChapterDisplay
    {
            public string? ChapCountry { get; set; }
        public string ChapLanguage { get; set; }
        public string? ChapLanguageIETF { get; set; }
        public string ChapString { get; set; }
    }

    public sealed class Chapters
    {
            public string? ChapCountry { get; set; }
        public string ChapLanguage { get; set; }
        public string? ChapLanguageIETF { get; set; }
        public ulong ChapProcessCodecID { get; set; }
        public byte[]? ChapProcessData { get; set; }
        public byte[]? ChapProcessPrivate { get; set; }
        public ulong ChapProcessTime { get; set; }
        public string ChapString { get; set; }
        public ulong ChapterFlagEnabled { get; set; }
        public ulong ChapterFlagHidden { get; set; }
        public ulong? ChapterPhysicalEquiv { get; set; }
        public ulong? ChapterSegmentEditionUID { get; set; }
        public byte[]? ChapterSegmentUID { get; set; }
        public string? ChapterStringUID { get; set; }
        public ulong? ChapterTimeEnd { get; set; }
        public ulong ChapterTimeStart { get; set; }
        public ulong ChapterTrackUID { get; set; }
        public ulong ChapterUID { get; set; }
        public ulong EditionFlagDefault { get; set; }
        public ulong EditionFlagHidden { get; set; }
        public ulong? EditionFlagOrdered { get; set; }
        public ulong? EditionUID { get; set; }
    }

    public sealed class ChapterTrack
    {
            public ulong ChapterTrackUID { get; set; }
    }

    public sealed class ChapterTranslate
    {
            public ulong ChapterTranslateCodec { get; set; }
        public ulong? ChapterTranslateEditionUID { get; set; }
        public byte[]? ChapterTranslateID { get; set; }
    }

    public sealed class Cluster
    {
            public ulong BlockAddID { get; set; }
        public byte[]? BlockAdditional { get; set; }
        public ulong? BlockAdditionID { get; set; }
        public ulong? BlockDuration { get; set; }
        public byte[]? BlockVirtual { get; set; }
        public byte[]? CodecState { get; set; }
        public ulong? Delay { get; set; }
        public long? DiscardPadding { get; set; }
        public byte[]? EncryptedBlock { get; set; }
        public ulong? FrameNumber { get; set; }
        public ulong? LaceNumber { get; set; }
        public ulong? Position { get; set; }
        public ulong? PrevSize { get; set; }
        public long? ReferenceBlock { get; set; }
        public ulong ReferenceOffset { get; set; }
        public ulong ReferencePriority { get; set; }
        public ulong ReferenceTimestamp { get; set; }
        public long? ReferenceVirtual { get; set; }
        public ulong? SilentTrackNumber { get; set; }
        public ulong? SliceDuration { get; set; }
        public ulong Timestamp { get; set; }
    }

    public sealed class Colour
    {
            public ulong? BitsPerChannel { get; set; }
        public ulong? CbSubsamplingHorz { get; set; }
        public ulong? CbSubsamplingVert { get; set; }
        public ulong? ChromaSitingHorz { get; set; }
        public ulong? ChromaSitingVert { get; set; }
        public ulong? ChromaSubsamplingHorz { get; set; }
        public ulong? ChromaSubsamplingVert { get; set; }
        public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public ulong? MatrixCoefficients { get; set; }
        public ulong? MaxCLL { get; set; }
        public ulong? MaxFALL { get; set; }
        public ulong? Primaries { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public ulong? Range { get; set; }
        public ulong? TransferCharacteristics { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
    }

    public sealed class ContentCompression
    {
            public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
    }

    public sealed class ContentEncAESSettings
    {
            public ulong AESSettingsCipherMode { get; set; }
    }

    public sealed class ContentEncoding
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong ContentEncodingOrder { get; set; }
        public ulong ContentEncodingScope { get; set; }
        public ulong ContentEncodingType { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
    }

    public sealed class ContentEncodings
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong ContentEncodingOrder { get; set; }
        public ulong ContentEncodingScope { get; set; }
        public ulong ContentEncodingType { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
    }

    public sealed class ContentEncryption
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
    }

    public sealed class CuePoint
    {
            public ulong? CueBlockNumber { get; set; }
        public ulong CueClusterPosition { get; set; }
        public ulong? CueCodecState { get; set; }
        public ulong? CueDuration { get; set; }
        public ulong CueRefCluster { get; set; }
        public ulong? CueRefCodecState { get; set; }
        public ulong? CueRefNumber { get; set; }
        public ulong CueRefTime { get; set; }
        public ulong? CueRelativePosition { get; set; }
        public ulong CueTime { get; set; }
        public ulong CueTrack { get; set; }
    }

    public sealed class CueReference
    {
            public ulong CueRefCluster { get; set; }
        public ulong? CueRefCodecState { get; set; }
        public ulong? CueRefNumber { get; set; }
        public ulong CueRefTime { get; set; }
    }

    public sealed class Cues
    {
            public ulong? CueBlockNumber { get; set; }
        public ulong CueClusterPosition { get; set; }
        public ulong? CueCodecState { get; set; }
        public ulong? CueDuration { get; set; }
        public ulong CueRefCluster { get; set; }
        public ulong? CueRefCodecState { get; set; }
        public ulong? CueRefNumber { get; set; }
        public ulong CueRefTime { get; set; }
        public ulong? CueRelativePosition { get; set; }
        public ulong CueTime { get; set; }
        public ulong CueTrack { get; set; }
    }

    public sealed class CueTrackPositions
    {
            public ulong? CueBlockNumber { get; set; }
        public ulong CueClusterPosition { get; set; }
        public ulong? CueCodecState { get; set; }
        public ulong? CueDuration { get; set; }
        public ulong CueRefCluster { get; set; }
        public ulong? CueRefCodecState { get; set; }
        public ulong? CueRefNumber { get; set; }
        public ulong CueRefTime { get; set; }
        public ulong? CueRelativePosition { get; set; }
        public ulong CueTrack { get; set; }
    }

    public sealed class EditionEntry
    {
            public string? ChapCountry { get; set; }
        public string ChapLanguage { get; set; }
        public string? ChapLanguageIETF { get; set; }
        public ulong ChapProcessCodecID { get; set; }
        public byte[]? ChapProcessData { get; set; }
        public byte[]? ChapProcessPrivate { get; set; }
        public ulong ChapProcessTime { get; set; }
        public string ChapString { get; set; }
        public ulong ChapterFlagEnabled { get; set; }
        public ulong ChapterFlagHidden { get; set; }
        public ulong? ChapterPhysicalEquiv { get; set; }
        public ulong? ChapterSegmentEditionUID { get; set; }
        public byte[]? ChapterSegmentUID { get; set; }
        public string? ChapterStringUID { get; set; }
        public ulong? ChapterTimeEnd { get; set; }
        public ulong ChapterTimeStart { get; set; }
        public ulong ChapterTrackUID { get; set; }
        public ulong ChapterUID { get; set; }
        public ulong EditionFlagDefault { get; set; }
        public ulong EditionFlagHidden { get; set; }
        public ulong? EditionFlagOrdered { get; set; }
        public ulong? EditionUID { get; set; }
    }

    public sealed class Info
    {
            public ulong ChapterTranslateCodec { get; set; }
        public ulong? ChapterTranslateEditionUID { get; set; }
        public byte[]? ChapterTranslateID { get; set; }
        public DateTime? DateUTC { get; set; }
        public float? Duration { get; set; }
        public string MuxingApp { get; set; }
        public string? NextFilename { get; set; }
        public byte[]? NextUID { get; set; }
        public string? PrevFilename { get; set; }
        public byte[]? PrevUID { get; set; }
        public byte[]? SegmentFamily { get; set; }
        public string? SegmentFilename { get; set; }
        public byte[]? SegmentUID { get; set; }
        public ulong TimestampScale { get; set; }
        public string? Title { get; set; }
        public string WritingApp { get; set; }
    }

    public sealed class MasteringMetadata
    {
            public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
    }

    public sealed class Projection
    {
            public float ProjectionPosePitch { get; set; }
        public float ProjectionPoseRoll { get; set; }
        public float ProjectionPoseYaw { get; set; }
        public byte[]? ProjectionPrivate { get; set; }
        public ulong ProjectionType { get; set; }
    }

    public sealed class ReferenceFrame
    {
            public ulong ReferenceOffset { get; set; }
        public ulong ReferenceTimestamp { get; set; }
    }

    public sealed class Seek
    {
            public byte[]? SeekID { get; set; }
        public ulong SeekPosition { get; set; }
    }

    public sealed class SeekHead
    {
            public byte[]? SeekID { get; set; }
        public ulong SeekPosition { get; set; }
    }

    public sealed class Segment
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong? AlphaMode { get; set; }
        public ulong? AspectRatioType { get; set; }
        public ulong? AttachmentLink { get; set; }
        public ulong? BitDepth { get; set; }
        public ulong? BitsPerChannel { get; set; }
        public ulong BlockAddID { get; set; }
        public byte[]? BlockAddIDExtraData { get; set; }
        public string? BlockAddIDName { get; set; }
        public ulong BlockAddIDType { get; set; }
        public ulong? BlockAddIDValue { get; set; }
        public byte[]? BlockAdditional { get; set; }
        public ulong? BlockAdditionID { get; set; }
        public ulong? BlockDuration { get; set; }
        public byte[]? BlockVirtual { get; set; }
        public ulong? CbSubsamplingHorz { get; set; }
        public ulong? CbSubsamplingVert { get; set; }
        public byte[]? ChannelPositions { get; set; }
        public ulong Channels { get; set; }
        public string? ChapCountry { get; set; }
        public string ChapLanguage { get; set; }
        public string? ChapLanguageIETF { get; set; }
        public ulong ChapProcessCodecID { get; set; }
        public byte[]? ChapProcessData { get; set; }
        public byte[]? ChapProcessPrivate { get; set; }
        public ulong ChapProcessTime { get; set; }
        public string ChapString { get; set; }
        public ulong ChapterFlagEnabled { get; set; }
        public ulong ChapterFlagHidden { get; set; }
        public ulong? ChapterPhysicalEquiv { get; set; }
        public ulong? ChapterSegmentEditionUID { get; set; }
        public byte[]? ChapterSegmentUID { get; set; }
        public string? ChapterStringUID { get; set; }
        public ulong? ChapterTimeEnd { get; set; }
        public ulong ChapterTimeStart { get; set; }
        public ulong ChapterTrackUID { get; set; }
        public ulong ChapterTranslateCodec { get; set; }
        public ulong? ChapterTranslateEditionUID { get; set; }
        public byte[]? ChapterTranslateID { get; set; }
        public ulong ChapterUID { get; set; }
        public ulong? ChromaSitingHorz { get; set; }
        public ulong? ChromaSitingVert { get; set; }
        public ulong? ChromaSubsamplingHorz { get; set; }
        public ulong? ChromaSubsamplingVert { get; set; }
        public ulong CodecDecodeAll { get; set; }
        public ulong? CodecDelay { get; set; }
        public string? CodecDownloadURL { get; set; }
        public string CodecID { get; set; }
        public string? CodecInfoURL { get; set; }
        public string? CodecName { get; set; }
        public byte[]? CodecPrivate { get; set; }
        public string? CodecSettings { get; set; }
        public byte[]? CodecState { get; set; }
        public byte[]? ColourSpace { get; set; }
        public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong ContentEncodingOrder { get; set; }
        public ulong ContentEncodingScope { get; set; }
        public ulong ContentEncodingType { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
        public ulong? CueBlockNumber { get; set; }
        public ulong CueClusterPosition { get; set; }
        public ulong? CueCodecState { get; set; }
        public ulong? CueDuration { get; set; }
        public ulong CueRefCluster { get; set; }
        public ulong? CueRefCodecState { get; set; }
        public ulong? CueRefNumber { get; set; }
        public ulong CueRefTime { get; set; }
        public ulong? CueRelativePosition { get; set; }
        public ulong CueTime { get; set; }
        public ulong CueTrack { get; set; }
        public DateTime? DateUTC { get; set; }
        public ulong? DefaultDecodedFieldDuration { get; set; }
        public ulong? DefaultDuration { get; set; }
        public ulong? Delay { get; set; }
        public long? DiscardPadding { get; set; }
        public ulong? DisplayHeight { get; set; }
        public ulong? DisplayUnit { get; set; }
        public ulong? DisplayWidth { get; set; }
        public float? Duration { get; set; }
        public ulong EditionFlagDefault { get; set; }
        public ulong EditionFlagHidden { get; set; }
        public ulong? EditionFlagOrdered { get; set; }
        public ulong? EditionUID { get; set; }
        public byte[]? EncryptedBlock { get; set; }
        public ulong FieldOrder { get; set; }
        public byte[]? FileData { get; set; }
        public string? FileDescription { get; set; }
        public string FileMimeType { get; set; }
        public string FileName { get; set; }
        public byte[]? FileReferral { get; set; }
        public ulong FileUID { get; set; }
        public ulong? FileUsedEndTime { get; set; }
        public ulong? FileUsedStartTime { get; set; }
        public ulong FlagDefault { get; set; }
        public ulong FlagEnabled { get; set; }
        public ulong FlagForced { get; set; }
        public ulong FlagInterlaced { get; set; }
        public ulong FlagLacing { get; set; }
        public ulong? FrameNumber { get; set; }
        public float? FrameRate { get; set; }
        public float? GammaValue { get; set; }
        public ulong? LaceNumber { get; set; }
        public string? Language { get; set; }
        public string? LanguageIETF { get; set; }
        public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public ulong? MatrixCoefficients { get; set; }
        public ulong MaxBlockAdditionID { get; set; }
        public ulong? MaxCache { get; set; }
        public ulong? MaxCLL { get; set; }
        public ulong? MaxFALL { get; set; }
        public ulong MinCache { get; set; }
        public string MuxingApp { get; set; }
        public string? Name { get; set; }
        public string? NextFilename { get; set; }
        public byte[]? NextUID { get; set; }
        public ulong? OldStereoMode { get; set; }
        public float? OutputSamplingFrequency { get; set; }
        public ulong? PixelCropBottom { get; set; }
        public ulong? PixelCropLeft { get; set; }
        public ulong? PixelCropRight { get; set; }
        public ulong? PixelCropTop { get; set; }
        public ulong PixelHeight { get; set; }
        public ulong PixelWidth { get; set; }
        public ulong? Position { get; set; }
        public string? PrevFilename { get; set; }
        public ulong? PrevSize { get; set; }
        public byte[]? PrevUID { get; set; }
        public ulong? Primaries { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public float ProjectionPosePitch { get; set; }
        public float ProjectionPoseRoll { get; set; }
        public float ProjectionPoseYaw { get; set; }
        public byte[]? ProjectionPrivate { get; set; }
        public ulong ProjectionType { get; set; }
        public ulong? Range { get; set; }
        public long? ReferenceBlock { get; set; }
        public ulong ReferenceOffset { get; set; }
        public ulong ReferencePriority { get; set; }
        public ulong ReferenceTimestamp { get; set; }
        public long? ReferenceVirtual { get; set; }
        public float SamplingFrequency { get; set; }
        public byte[]? SeekID { get; set; }
        public ulong SeekPosition { get; set; }
        public ulong SeekPreRoll { get; set; }
        public byte[]? SegmentFamily { get; set; }
        public string? SegmentFilename { get; set; }
        public byte[]? SegmentUID { get; set; }
        public ulong? SilentTrackNumber { get; set; }
        public ulong? SliceDuration { get; set; }
        public ulong? StereoMode { get; set; }
        public ulong? TagAttachmentUID { get; set; }
        public byte[]? TagBinary { get; set; }
        public ulong? TagChapterUID { get; set; }
        public ulong TagDefault { get; set; }
        public ulong? TagEditionUID { get; set; }
        public string TagLanguage { get; set; }
        public string? TagLanguageIETF { get; set; }
        public string TagName { get; set; }
        public string? TagString { get; set; }
        public ulong? TagTrackUID { get; set; }
        public string? TargetType { get; set; }
        public ulong? TargetTypeValue { get; set; }
        public ulong Timestamp { get; set; }
        public ulong TimestampScale { get; set; }
        public string? Title { get; set; }
        public ulong TrackJoinUID { get; set; }
        public ulong TrackNumber { get; set; }
        public long? TrackOffset { get; set; }
        public ulong? TrackOverlay { get; set; }
        public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
        public float TrackTimestampScale { get; set; }
        public ulong TrackTranslateCodec { get; set; }
        public ulong? TrackTranslateEditionUID { get; set; }
        public byte[]? TrackTranslateTrackID { get; set; }
        public ulong TrackType { get; set; }
        public ulong TrackUID { get; set; }
        public ulong? TransferCharacteristics { get; set; }
        public byte[]? TrickMasterTrackSegmentUID { get; set; }
        public ulong? TrickMasterTrackUID { get; set; }
        public ulong? TrickTrackFlag { get; set; }
        public byte[]? TrickTrackSegmentUID { get; set; }
        public ulong? TrickTrackUID { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
        public string WritingApp { get; set; }
    }

    public sealed class SilentTracks
    {
            public ulong? SilentTrackNumber { get; set; }
    }

    public sealed class SimpleTag
    {
        }

    public sealed class Slices
    {
            public ulong? BlockAdditionID { get; set; }
        public ulong? Delay { get; set; }
        public ulong? FrameNumber { get; set; }
        public ulong? LaceNumber { get; set; }
        public ulong? SliceDuration { get; set; }
    }

    public sealed class Tag
    {
            public ulong? TagAttachmentUID { get; set; }
        public byte[]? TagBinary { get; set; }
        public ulong? TagChapterUID { get; set; }
        public ulong TagDefault { get; set; }
        public ulong? TagEditionUID { get; set; }
        public string TagLanguage { get; set; }
        public string? TagLanguageIETF { get; set; }
        public string TagName { get; set; }
        public string? TagString { get; set; }
        public ulong? TagTrackUID { get; set; }
        public string? TargetType { get; set; }
        public ulong? TargetTypeValue { get; set; }
    }

    public sealed class Tags
    {
            public ulong? TagAttachmentUID { get; set; }
        public byte[]? TagBinary { get; set; }
        public ulong? TagChapterUID { get; set; }
        public ulong TagDefault { get; set; }
        public ulong? TagEditionUID { get; set; }
        public string TagLanguage { get; set; }
        public string? TagLanguageIETF { get; set; }
        public string TagName { get; set; }
        public string? TagString { get; set; }
        public ulong? TagTrackUID { get; set; }
        public string? TargetType { get; set; }
        public ulong? TargetTypeValue { get; set; }
    }

    public sealed class Targets
    {
            public ulong? TagAttachmentUID { get; set; }
        public ulong? TagChapterUID { get; set; }
        public ulong? TagEditionUID { get; set; }
        public ulong? TagTrackUID { get; set; }
        public string? TargetType { get; set; }
        public ulong? TargetTypeValue { get; set; }
    }

    public sealed class TimeSlice
    {
            public ulong? BlockAdditionID { get; set; }
        public ulong? Delay { get; set; }
        public ulong? FrameNumber { get; set; }
        public ulong? LaceNumber { get; set; }
        public ulong? SliceDuration { get; set; }
    }

    public sealed class TrackCombinePlanes
    {
            public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
    }

    public sealed class TrackEntry
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong? AlphaMode { get; set; }
        public ulong? AspectRatioType { get; set; }
        public ulong? AttachmentLink { get; set; }
        public ulong? BitDepth { get; set; }
        public ulong? BitsPerChannel { get; set; }
        public byte[]? BlockAddIDExtraData { get; set; }
        public string? BlockAddIDName { get; set; }
        public ulong BlockAddIDType { get; set; }
        public ulong? BlockAddIDValue { get; set; }
        public ulong? CbSubsamplingHorz { get; set; }
        public ulong? CbSubsamplingVert { get; set; }
        public byte[]? ChannelPositions { get; set; }
        public ulong Channels { get; set; }
        public ulong? ChromaSitingHorz { get; set; }
        public ulong? ChromaSitingVert { get; set; }
        public ulong? ChromaSubsamplingHorz { get; set; }
        public ulong? ChromaSubsamplingVert { get; set; }
        public ulong CodecDecodeAll { get; set; }
        public ulong? CodecDelay { get; set; }
        public string? CodecDownloadURL { get; set; }
        public string CodecID { get; set; }
        public string? CodecInfoURL { get; set; }
        public string? CodecName { get; set; }
        public byte[]? CodecPrivate { get; set; }
        public string? CodecSettings { get; set; }
        public byte[]? ColourSpace { get; set; }
        public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong ContentEncodingOrder { get; set; }
        public ulong ContentEncodingScope { get; set; }
        public ulong ContentEncodingType { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
        public ulong? DefaultDecodedFieldDuration { get; set; }
        public ulong? DefaultDuration { get; set; }
        public ulong? DisplayHeight { get; set; }
        public ulong? DisplayUnit { get; set; }
        public ulong? DisplayWidth { get; set; }
        public ulong FieldOrder { get; set; }
        public ulong FlagDefault { get; set; }
        public ulong FlagEnabled { get; set; }
        public ulong FlagForced { get; set; }
        public ulong FlagInterlaced { get; set; }
        public ulong FlagLacing { get; set; }
        public float? FrameRate { get; set; }
        public float? GammaValue { get; set; }
        public string? Language { get; set; }
        public string? LanguageIETF { get; set; }
        public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public ulong? MatrixCoefficients { get; set; }
        public ulong MaxBlockAdditionID { get; set; }
        public ulong? MaxCache { get; set; }
        public ulong? MaxCLL { get; set; }
        public ulong? MaxFALL { get; set; }
        public ulong MinCache { get; set; }
        public string? Name { get; set; }
        public ulong? OldStereoMode { get; set; }
        public float? OutputSamplingFrequency { get; set; }
        public ulong? PixelCropBottom { get; set; }
        public ulong? PixelCropLeft { get; set; }
        public ulong? PixelCropRight { get; set; }
        public ulong? PixelCropTop { get; set; }
        public ulong PixelHeight { get; set; }
        public ulong PixelWidth { get; set; }
        public ulong? Primaries { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public float ProjectionPosePitch { get; set; }
        public float ProjectionPoseRoll { get; set; }
        public float ProjectionPoseYaw { get; set; }
        public byte[]? ProjectionPrivate { get; set; }
        public ulong ProjectionType { get; set; }
        public ulong? Range { get; set; }
        public float SamplingFrequency { get; set; }
        public ulong SeekPreRoll { get; set; }
        public ulong? StereoMode { get; set; }
        public ulong TrackJoinUID { get; set; }
        public ulong TrackNumber { get; set; }
        public long? TrackOffset { get; set; }
        public ulong? TrackOverlay { get; set; }
        public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
        public float TrackTimestampScale { get; set; }
        public ulong TrackTranslateCodec { get; set; }
        public ulong? TrackTranslateEditionUID { get; set; }
        public byte[]? TrackTranslateTrackID { get; set; }
        public ulong TrackType { get; set; }
        public ulong TrackUID { get; set; }
        public ulong? TransferCharacteristics { get; set; }
        public byte[]? TrickMasterTrackSegmentUID { get; set; }
        public ulong? TrickMasterTrackUID { get; set; }
        public ulong? TrickTrackFlag { get; set; }
        public byte[]? TrickTrackSegmentUID { get; set; }
        public ulong? TrickTrackUID { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
    }

    public sealed class TrackJoinBlocks
    {
            public ulong TrackJoinUID { get; set; }
    }

    public sealed class TrackOperation
    {
            public ulong TrackJoinUID { get; set; }
        public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
    }

    public sealed class TrackPlane
    {
            public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
    }

    public sealed class Tracks
    {
            public ulong AESSettingsCipherMode { get; set; }
        public ulong? AlphaMode { get; set; }
        public ulong? AspectRatioType { get; set; }
        public ulong? AttachmentLink { get; set; }
        public ulong? BitDepth { get; set; }
        public ulong? BitsPerChannel { get; set; }
        public byte[]? BlockAddIDExtraData { get; set; }
        public string? BlockAddIDName { get; set; }
        public ulong BlockAddIDType { get; set; }
        public ulong? BlockAddIDValue { get; set; }
        public ulong? CbSubsamplingHorz { get; set; }
        public ulong? CbSubsamplingVert { get; set; }
        public byte[]? ChannelPositions { get; set; }
        public ulong Channels { get; set; }
        public ulong? ChromaSitingHorz { get; set; }
        public ulong? ChromaSitingVert { get; set; }
        public ulong? ChromaSubsamplingHorz { get; set; }
        public ulong? ChromaSubsamplingVert { get; set; }
        public ulong CodecDecodeAll { get; set; }
        public ulong? CodecDelay { get; set; }
        public string? CodecDownloadURL { get; set; }
        public string CodecID { get; set; }
        public string? CodecInfoURL { get; set; }
        public string? CodecName { get; set; }
        public byte[]? CodecPrivate { get; set; }
        public string? CodecSettings { get; set; }
        public byte[]? ColourSpace { get; set; }
        public ulong ContentCompAlgo { get; set; }
        public byte[]? ContentCompSettings { get; set; }
        public ulong ContentEncAlgo { get; set; }
        public byte[]? ContentEncKeyID { get; set; }
        public ulong ContentEncodingOrder { get; set; }
        public ulong ContentEncodingScope { get; set; }
        public ulong ContentEncodingType { get; set; }
        public ulong? ContentSigAlgo { get; set; }
        public ulong? ContentSigHashAlgo { get; set; }
        public byte[]? ContentSigKeyID { get; set; }
        public byte[]? ContentSignature { get; set; }
        public ulong? DefaultDecodedFieldDuration { get; set; }
        public ulong? DefaultDuration { get; set; }
        public ulong? DisplayHeight { get; set; }
        public ulong? DisplayUnit { get; set; }
        public ulong? DisplayWidth { get; set; }
        public ulong FieldOrder { get; set; }
        public ulong FlagDefault { get; set; }
        public ulong FlagEnabled { get; set; }
        public ulong FlagForced { get; set; }
        public ulong FlagInterlaced { get; set; }
        public ulong FlagLacing { get; set; }
        public float? FrameRate { get; set; }
        public float? GammaValue { get; set; }
        public string? Language { get; set; }
        public string? LanguageIETF { get; set; }
        public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public ulong? MatrixCoefficients { get; set; }
        public ulong MaxBlockAdditionID { get; set; }
        public ulong? MaxCache { get; set; }
        public ulong? MaxCLL { get; set; }
        public ulong? MaxFALL { get; set; }
        public ulong MinCache { get; set; }
        public string? Name { get; set; }
        public ulong? OldStereoMode { get; set; }
        public float? OutputSamplingFrequency { get; set; }
        public ulong? PixelCropBottom { get; set; }
        public ulong? PixelCropLeft { get; set; }
        public ulong? PixelCropRight { get; set; }
        public ulong? PixelCropTop { get; set; }
        public ulong PixelHeight { get; set; }
        public ulong PixelWidth { get; set; }
        public ulong? Primaries { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public float ProjectionPosePitch { get; set; }
        public float ProjectionPoseRoll { get; set; }
        public float ProjectionPoseYaw { get; set; }
        public byte[]? ProjectionPrivate { get; set; }
        public ulong ProjectionType { get; set; }
        public ulong? Range { get; set; }
        public float SamplingFrequency { get; set; }
        public ulong SeekPreRoll { get; set; }
        public ulong? StereoMode { get; set; }
        public ulong TrackJoinUID { get; set; }
        public ulong TrackNumber { get; set; }
        public long? TrackOffset { get; set; }
        public ulong? TrackOverlay { get; set; }
        public ulong TrackPlaneType { get; set; }
        public ulong TrackPlaneUID { get; set; }
        public float TrackTimestampScale { get; set; }
        public ulong TrackTranslateCodec { get; set; }
        public ulong? TrackTranslateEditionUID { get; set; }
        public byte[]? TrackTranslateTrackID { get; set; }
        public ulong TrackType { get; set; }
        public ulong TrackUID { get; set; }
        public ulong? TransferCharacteristics { get; set; }
        public byte[]? TrickMasterTrackSegmentUID { get; set; }
        public ulong? TrickMasterTrackUID { get; set; }
        public ulong? TrickTrackFlag { get; set; }
        public byte[]? TrickTrackSegmentUID { get; set; }
        public ulong? TrickTrackUID { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
    }

    public sealed class TrackTranslate
    {
            public ulong TrackTranslateCodec { get; set; }
        public ulong? TrackTranslateEditionUID { get; set; }
        public byte[]? TrackTranslateTrackID { get; set; }
    }

    public sealed class Video
    {
            public ulong? AlphaMode { get; set; }
        public ulong? AspectRatioType { get; set; }
        public ulong? BitsPerChannel { get; set; }
        public ulong? CbSubsamplingHorz { get; set; }
        public ulong? CbSubsamplingVert { get; set; }
        public ulong? ChromaSitingHorz { get; set; }
        public ulong? ChromaSitingVert { get; set; }
        public ulong? ChromaSubsamplingHorz { get; set; }
        public ulong? ChromaSubsamplingVert { get; set; }
        public byte[]? ColourSpace { get; set; }
        public ulong? DisplayHeight { get; set; }
        public ulong? DisplayUnit { get; set; }
        public ulong? DisplayWidth { get; set; }
        public ulong FieldOrder { get; set; }
        public ulong FlagInterlaced { get; set; }
        public float? FrameRate { get; set; }
        public float? GammaValue { get; set; }
        public float? LuminanceMax { get; set; }
        public float? LuminanceMin { get; set; }
        public ulong? MatrixCoefficients { get; set; }
        public ulong? MaxCLL { get; set; }
        public ulong? MaxFALL { get; set; }
        public ulong? OldStereoMode { get; set; }
        public ulong? PixelCropBottom { get; set; }
        public ulong? PixelCropLeft { get; set; }
        public ulong? PixelCropRight { get; set; }
        public ulong? PixelCropTop { get; set; }
        public ulong PixelHeight { get; set; }
        public ulong PixelWidth { get; set; }
        public ulong? Primaries { get; set; }
        public float? PrimaryBChromaticityX { get; set; }
        public float? PrimaryBChromaticityY { get; set; }
        public float? PrimaryGChromaticityX { get; set; }
        public float? PrimaryGChromaticityY { get; set; }
        public float? PrimaryRChromaticityX { get; set; }
        public float? PrimaryRChromaticityY { get; set; }
        public float ProjectionPosePitch { get; set; }
        public float ProjectionPoseRoll { get; set; }
        public float ProjectionPoseYaw { get; set; }
        public byte[]? ProjectionPrivate { get; set; }
        public ulong ProjectionType { get; set; }
        public ulong? Range { get; set; }
        public ulong? StereoMode { get; set; }
        public ulong? TransferCharacteristics { get; set; }
        public float? WhitePointChromaticityX { get; set; }
        public float? WhitePointChromaticityY { get; set; }
    }

}
*/